# Compatibility: v1.58.0
# This is a minimalist configuration file for golangci-lint with selective overrides of defaults.
# See the .golangci-lint.yml.reference file in the source repo for the version of golangci-lint you are using:
# https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml

linters:
  disable-all: true
  enable:
    - bodyclose
    - errcheck
    - exportloopref
    - gci
    - gosec
    - gosimple
    - govet
    - ineffassign
    - nakedret
    - noctx
    - nolintlint
    - staticcheck
    - unconvert
    - unparam
    - unused

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/gametimesf/ecs-deploy)
