# installation: `pre-commit install -t pre-commit -t commit-msg`
---
default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  # ensure commit message follows conventional commit
  # https://www.conventionalcommits.org/en/v1.0.0/
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.10.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional@v18.4.3']

  # basic checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args:
          - "--markdown-linebreak-ext=md"
        exclude: .py

  # detect secrets in commits
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        exclude: .git

  # linting yaml files
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.29.0
    hooks:
      - id: yamllint
        args:
          - "-d relaxed"
